config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  
  resources :listings

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :listing
end

app/models/listing.rb
class Listing < ApplicationRecord
    belongs_to :user
    has_many :users, through: :bookings
    has_many :bookings
    has_one_attached :photo
    # has_many_attached :photos

    SIZE = ["S", "M", "L", "XL", "ХХL"]
    CATEGORY = ["Фармерки", "Панталони","Кратки Панталнои","Хеланки","Сукња","Кошула","Топ","Палто","Фустан","Блуза","Сако","Комплет","Тренерки"]
    validates :title, presence: true
    validates :category,presence: true
    validates :price, presence: true
    validates :size, presence: true
    validates :description, presence: true
    validates :size, inclusion: { in: SIZE, message: "Невалидна категорија" }
    validates :category, inclusion: { in: CATEGORY, message: "Невалидна категорија" }


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def index #read all
    @listings = Listing.all
    end

  def show
    @listing = Listing.find(params[:id])
  end

  def new
    @listing = Listing.new
  end
  
  def create
    @listing = Listing.new(listing_params)
    @listing.save
    redirect_to listings_path(@listing)
  end

  private
    
  def listing_params
    params.require(:listing).permit(:title, :category, :price, :size, :description, :photo)
  end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    skip_before_action :authenticate_user!, only: :home

    def home
    end

    def contact
    end

    def about
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyShopPapi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/listings/index.html.erb
<ul>
  <% @listings.each do |listing| %>
    <li><%= listing.title %></li>
    <%= cl_image_tag @listing.photo.key, height: 300, width: 400, crop: :fill %>
  <% end %>
</ul>

app/views/listings/new.html.erb
<div class="container mt-5">

    <%= simple_form_for(@listing) do |f| %>
    <%= f.input :title, label: "Име на продукт", placeholder: "пр.: Блуза" %>
    <%= f.input :category, label: "Категорија", placeholder: "пр.: Џемпери" %>
    <%= f.input :price, label: "Цена", placeholder: "пр.: 1000 ден" %>
    <%= f.input :size, label: "Големина", placeholder: "пр.: S/M/L/XL/XXL" %>
    <%= f.input :description, label: "Опис", placeholder: "пр.: Еднобојна, струкирана ролка во кафеава боја" %>
    <%= f.input :photo, as: :file %>
    <%= submit_tag "Креирај Оглас", class: "btn btn-lg btn-success" %>
<% end %>
</div>

app/views/listings/show.html.erb
<h2><%= @listing.title %></h2>
<p><%= @listing.category %></p>
<p><%= @listing.price%></p>

app/views/pages/about.html.erb
<h1>about</h1>

app/views/pages/contact.html.erb
<h1>contact</h1>

app/views/pages/home.html.erb
<div>
    <!-- Navbar -->
  <div>
  <nav class="navbar-container">
      <ul class="nav navbar">
              <li class="nav-item active"><%= link_to  "Почетна", root_path%></li>
              <li class="nav-item"><%="За Нас"%></li>
              <li class="nav-item"><%="Производи"%></li>
              <li class="nav-item"><%="Reviews"%></li>
              <li class="nav-item"><%="Kонтакт"%></li>
      </ul>
  </nav>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://res.cloudinary.com/daf0zj13q/image/upload/v1610624801/artem-beliaikin-UdQt3FT6rxM-unsplash_p6sfql.jpg');">
  <div class="container">
    <h2 class="neon">WELCOME TO<br>MY SHOP PAPI</h2>
    <%= link_to 'ПОВЕЌЕ', new_listing_path, class: "btn btn-ghost" %>
  </div>
  </div>
  <div class="container">
    <p> Najnovi produkti </p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.instagram.com/aspesia__par/"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/My-Shop-Papi-733684480305626"><i class="fab fa-facebook"></i></a>
  </div>
  <div class="footer-copyright">
    2021 © MY SHOP PAPI <i class="fas fa-heart"></i>
  </div>
</div>